services:
  postgres:
    image: postgres:16
    container_name: pravotech-articles-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: articles_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pravotech-articles-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sometest.com
      PGADMIN_DEFAULT_PASSWORD: testpwnotsecure
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  webapi:
    container_name: pravotech-articles-webapi
    build:
      context: ..
      dockerfile: src/Pravotech.Articles.WebApi/Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ArticlesDatabase: Host=postgres;Port=5432;Database=articles_db;Username=postgres;Password=postgres
    ports:
      - "5000:8080"

volumes:
  postgres_data:
  pgadmin_data:
